# -*- coding: utf-8 -*-
"""lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/DvoryanovD/d8ebe4ea1600484cee1433c8c0007900/lab2.ipynb
"""

import numpy as np
from matplotlib import pyplot as plt
from tensorflow import keras
from tensorflow.keras.datasets import mnist
from tensorflow.keras.layers import Dense, Flatten

# Подготавливаем данные для обучения
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train / 255
x_test = x_test / 255
y_train_cat = keras.utils.to_categorical(y_train, 10)
y_test_cat = keras.utils.to_categorical(y_test, 10)

# Задаем модель НС (линейная функция активации)
model = keras.Sequential([
    Flatten(input_shape=(28, 28, 1)),
    Dense(46, activation='linear'),
    Dense(10, activation='linear')
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Производим обучение
model.fit(x_train, y_train_cat, batch_size=16, epochs=5, validation_split=0.2)

print('Метрики для тестовой выборки: ')
model.evaluate(x_test, y_test_cat)

print('Данные о модели: ')
print(model.summary())

# Задаем модель НС (логическая функция активации)
model = keras.Sequential([
    Flatten(input_shape=(28, 28, 1)),
    Dense(46, activation='sigmoid'),
    Dense(10, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Производим обучение
model.fit(x_train, y_train_cat, batch_size=16, epochs=5, validation_split=0.2)

print('Метрики для тестовой выборки: ')
model.evaluate(x_test, y_test_cat)

print('Данные о модели: ')
print(model.summary())


# Задаем модель НС (логическая функция ReLu)
model = keras.Sequential([
    Flatten(input_shape=(28, 28, 1)),
    Dense(46, activation='relu'),
    Dense(10, activation='relu')
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Производим обучение
model.fit(x_train, y_train_cat, batch_size=16, epochs=5, validation_split=0.2)

print('Метрики для тестовой выборки: ')
model.evaluate(x_test, y_test_cat)

print('Данные о модели: ')
print(model.summary())