# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14oZePRoStz_AdjfMKsHylwf8x1sUjM2q
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow import keras
from tensorflow.keras.layers import Dense

"""Обучающая выборка"""

c = np.array([[4,13,22],
              [17,15,-1],
              [5,-10,9],
              [-6,-3,10],
              [2,7,14],
              [-9,-5,-18],
              ])
f = np.array([96, 44, 12, 18, 58, -73])

model = keras.Sequential()

model.add(Dense(units=1, input_shape=(3,),activation='linear'))
model.compile(loss='mean_squared_error',optimizer=keras.optimizers.Adam(0.1))
log = model.fit(c, f, epochs=500, verbose=0)
plt.plot(log.history['loss'])
plt.grid(True)
plt.show()

b = [3,2,1]
print(model.predict([b]))

print(model.get_weights())